profile/xorg: tiny tweaks

diff --git a/roles/xorg/files/xorg/xinitrc b/roles/xorg/files/xorg/xinitrc
--- a/roles/xorg/files/xorg/xinitrc
+++ b/roles/xorg/files/xorg/xinitrc
@@ -1,59 +1,28 @@
 #!/bin/sh
 
-# shellcheck disable=1090,1091
-# bypass non-constant source following
+# xinitrc --- Xorg setup
 
-#          ██          ██   ██
-#         ░░          ░░   ░██
-#  ██   ██ ██ ███████  ██ ██████
-# ░░██ ██ ░██░░██░░░██░██░░░██░
-#  ░░███  ░██ ░██  ░██░██  ░██
-#   ██░██ ░██ ░██  ░██░██  ░██
-#  ██ ░░██░██ ███  ░██░██  ░░██
-# ░░   ░░ ░░ ░░░   ░░ ░░    ░░
-# runs after executing `startx`
+# Commentary:
 
-# load defaults
-xinit_cfg_dir='/etc/X11/xinit/xinitrc.d'
-test -d "${xinit_cfg_dir}" && {
-    for f in "${xinit_cfg_dir}"/*.sh ; do
-        test -x "${f}" && . "${f}"
-    done
-    unset f
-}
-unset -v xinit_cfg_dir
+# This file runs right after the X session started, mainly used to run
+# the WM/DE.
+
+# Code:
+
+# shellcheck disable=SC1091
+
+# load Xorg preamble
+test -x "${XORGDIR:?}/xprofile" && . "${XORGDIR:?}/xprofile"
 
 # -----------------------------------------------------------------------------
-# Xorg settings
-# -----------------------------------------------------------------------------
-
-xrandr --dpi 92 &   # DPI defaulted to 1920x1080 24" screen
-xset s off &        # disable screensaver
-xset dpms 0 0 900 & # off-screen time
-# source Xresources and ensure it's loaded before running WM/DE
-xrdb "${XORGDIR}/xorg/Xresources" & xrdbflag=1
-test -n "${xrdbflag}" && wait "${xrdbflag}" && unset -v xrdbflag
-
-# load X start-up programs
-test -x "${XORGDIR}/xprofile" && . "${XORGDIR}/xprofile"
-
-# -----------------------------------------------------------------------------
-# graphical environment (window manager/desktop environment)
+# window manager/desktop environment
 # -----------------------------------------------------------------------------
 
 # default
-session=${1:-bspwm}
+session=${1}
 
 case ${session} in
-bspwm)
-    unset -v session
-
-    exec bspwm
-    ;;
-
 dwm)
-    unset -v session
-
     # the following is for switching between local version of dwm* instead of
     # another default one (e.g: NixOS' directories)
     dwm_local_p=
@@ -69,9 +38,8 @@ dwm)
     while :; do ${dwm} 2>"/tmp/dwm.log" >&2; done
     ;;
 *)
-    unset -v session
-    exec ${1}
+    exec bspwm
 
-    printf "\n\nError loading WM/DE\n"
+    printf '\n\nError loading WM/DE\n' >&2
     exit 1
 esac
