bash: prompt properly made this time

diff --git a/roles/bash/files/bashrc b/roles/bash/files/bashrc
--- a/roles/bash/files/bashrc
+++ b/roles/bash/files/bashrc
@@ -70,11 +70,82 @@ for f in ${SHDIR}/plugins/*; do
     test -x "${f}" && . "${f}"
 done
 
+# git-prompt settings
+export GIT_PS1_SHOWDIRTYSTATE=1
+export GIT_PS1_SHOWSTASHSTATE=1
+export GIT_PS1_SHOWUNTRACKEDFILES=1
+export GIT_PS1_SHOWUPSTREAM='auto'
+export GIT_PS1_SHOWUPSTREAM='verbose'
+export GIT_PS1_DESCRIBE_STYLE='branch'
+export GIT_PS1_SHOWCOLORHINTS=1
+
 # -----------------------------------------------------------------------------
 # prompt
 # -----------------------------------------------------------------------------
 
-PS1="\[\e[0;1;2;38;5;33m\][\[\e[0;38;5;197m\]\u\[\e[0;1;2;38;5;68m\]::\[\e[0;38;5;250m\]\h\[\e[0;1;2;38;5;33m\]] \[\e[0;1;2;38;5;33m\]@ \[\e[0;38;5;226m\]\w\n\[\e[0;1;2;38;5;33m\]╚══ \[\e[0;1;2;53;38;5;214m\]${?} \[\e[0;38;5;192m\]`__git_ps1 "(%s)"` \[\e[0;1;2;38;5;46m\]\$ \[\e[0m\]"
+export PROMPT_COMMAND=cprompt
+
+cprompt() {
+    local exit_status=${PIPESTATUS[-1]} # needs to be first
+    PS1=
+
+    ## colors
+    local res='\[\e[0m\]' # text/color reset
+
+    # regular                   # bold
+    local bla='\[\e[0;30m\]';   local b_bla='\[\e[1;30m\]';
+    local red='\[\e[0;31m\]';   local b_red='\[\e[1;31m\]';
+    local gre='\[\e[0;32m\]';   local b_gre='\[\e[1;32m\]';
+    local yel='\[\e[0;33m\]';   local b_yel='\[\e[1;33m\]';
+    local blu='\[\e[0;34m\]';   local b_blu='\[\e[1;34m\]';
+    local pur='\[\e[0;35m\]';   local b_pur='\[\e[1;35m\]';
+    local cya='\[\e[0;36m\]';   local b_cya='\[\e[1;36m\]';
+    local whi='\[\e[0;37m\]';   local b_whi='\[\e[1;37m\]';
+
+    # decor '['
+    PS1+="${blu}[${res}"
+
+    ## user
+    PS1+="${red}\u${res}"
+
+    # decor '::'
+    PS1+="${b_whi}::${res}"
+
+    ## host
+    PS1+="${cya}\h${res}"
+
+    # decor ']'
+    PS1+="${blu}]${res}"
+
+    # decor ' @ '
+    PS1+="${pur} @ ${res}"
+
+    ## working dir
+    PS1+="${b_yel}\w${res}"
+
+    ## git
+    PS1+=" ${cya}`__git_ps1 "(%s)"`${res}"
+
+    # newline
+    PS1+='\n'
+
+    # decor '╚══'
+    PS1+="${blu}╚══ ${res}"
+
+    ## exit status
+    # display exit status code only if non-zero
+    test 0 -ne ${exit_status} && PS1+="${b_red}${exit_status} ${res}"
+
+    # decor '$'
+    PS1+="${b_gre}$ ${res}"
+}
+
+# -----------------------------------------------------------------------------
+# misc
+# -----------------------------------------------------------------------------
+
+# source direnv (must be around the end)
+test -x "`command -v 'direnv'`" && eval "`direnv hook bash`"
 
 # cleanup
 unset -f nix_shell_p
